# Generated by Django 4.1.2 on 2022-10-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
    ]
