# Generated by Django 4.1.3 on 2022-11-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_enrolment_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=3),
        ),
        migrations.AlterField(
            model_name='class',
            name='zoom_link',
            field=models.URLField(blank=True),
        ),
    ]
